<?php
?>
<body>
<div class="header">
    <div class="menu">
        <div class="nav-menu">
            <ul>
                <li><a href="<?php echo Helpers::getUrlPage()?>story">Câu Chuyện</a></li>
                <li><a href="<?php echo Helpers::getUrlPage()?>news">Bảng Tin</a>
                    <div class="wrap-drop">
                        <ul>
                            <li><a href="<?php echo Helpers::getUrlPage()?>news">Cộng</a></li>
                            <li><a href="<?php echo Helpers::getUrlPage()?>news">Tin Tức</a></li>
                            <li><a href="<?php echo Helpers::getUrlPage()?>news">Tuyển Dụng</a></li>
                            <li><a href="<?php echo Helpers::getUrlPage()?>news">Đó Đây</a></li>
                            <li><a href="<?php echo Helpers::getUrlPage()?>news">Pha Chế</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="<?php echo Helpers::getUrlPage()?>product">Tạp Hóa</a>
                    <div class="wrap-drop">
                        <ul>
                            <li><a href="<?php echo Helpers::getUrlPage()?>product">Thực Đơn</a></li>
                            <li><a href="<?php echo Helpers::getUrlPage()?>product">Quầy Lưu Niệm</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
        <div class="logo-brand">
            <div class="brand">
                <a href="<?php echo Helpers::getUrlPage() ?>">
                    <img  src="<?php echo Helpers::getPathPublic('user')?>images/brand.png">
                </a>
            </div>
        </div>
        <div class="nav-menu">
            <ul>
                <li><a href="<?php echo Helpers::getUrlPage()?>recruitment">Tuyển Dụng</a>
                    <div class="wrap-drop">
                        <ul>
                            <li><a href="<?php echo Helpers::getUrlPage()?>recruitment">Ứng Tuyển</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="#">Cửa Hàng</a></li>
                <li><a href="<?php echo Helpers::getUrlPage()?>contact">Liên Hệ</a>
                    <div class="wrap-drop">
                        <ul>
                            <li><a href="<?php echo Helpers::getUrlPage()?>contact">Cộng Lắng Nghe</a></li>
                            <li><a href="<?php echo Helpers::getUrlPage()?>contact">Hợp Tác</a></li>
                            <li><a href="<?php echo Helpers::getUrlPage()?>contact" target="_blank">Về Chúng Tôi</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <!-- <div class="nation">
        <a href=""><img  src="<?php echo Helpers::getPathPublic('user')?>images/nation.png"></a>
    </div> -->
</div>
<div class="ajax-loading">
<div class="loading">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <g transform="translate(50 50)">
            <g transform="scale(0.7)">
                <g transform="translate(-50 -50)">
                    <g>
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="0.7575757575757576s"></animateTransform>
                        <path fill-opacity="0.8" fill="#facd9e" d="M50 50L50 0A50 50 0 0 1 100 50Z"></path>
                    </g>
                    <g>
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="1.0101010101010102s"></animateTransform>
                        <path fill-opacity="0.8" fill="#389798" d="M50 50L50 0A50 50 0 0 1 100 50Z" transform="rotate(90 50 50)"></path>
                    </g>
                    <g>
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="1.5151515151515151s"></animateTransform>
                        <path fill-opacity="0.8" fill="#459448" d="M50 50L50 0A50 50 0 0 1 100 50Z" transform="rotate(180 50 50)"></path>
                    </g>
                    <g>
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" values="0 50 50;360 50 50" keyTimes="0;1" dur="3.0303030303030303s"></animateTransform>
                        <path fill-opacity="0.8" fill="#f19d3b" d="M50 50L50 0A50 50 0 0 1 100 50Z" transform="rotate(270 50 50)"></path>
                    </g>
                </g>
            </g>
        </g>
        <!-- [ldio] generated by https://loading.io/ --></svg>
    </div>

</div>